
pulsar:
  protocol_url: ${PROTOCOL_URL}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    ddl-auto: none
    hibernate:
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true