version: '3'

services:

  python_pulsar_consumer:
    build: ./python-pulsar
    image: 'registry.njax.org/zelda-recipe/python-pulsar'
    env_file: ./.env
    environment:
      PROTOCOL_URL: 'pulsar://standalone:6650'
    depends_on:
      - 'standalone'
    entrypoint: [ /entrypoint.sh, consume ]

  python_pulsar_producer:
    build: ./python-pulsar
    image: 'registry.njax.org/zelda-recipe/python-pulsar'
    stdin_open: true
    tty: true
    env_file: ./.env
    environment:
      PROTOCOL_URL: 'pulsar://standalone:6650'
    depends_on:
      - 'standalone'
    entrypoint: [ /entrypoint.sh, produce ]


  java:
    build: ./java-api
    image: 'registry.njax.org/zelda-recipe/java-api'
    env_file: ./.env
    environment:
      PROTOCOL_URL: 'pulsar://standalone:6650'
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    volumes:
      - './java-api:/app'
    entrypoint: [ /entrypoint.sh, development_server ]

  #react:

#######################
#  Backing Services   #
#######################

## MySQL

  db:
    image: mysql:5.7
    restart: "no"
    ports:
      - "30409:3306"
    env_file:
      - ./.env
    volumes:
      - my-db-zelda:/var/lib/mysql

## Pulsar

  standalone:
    image: apachepulsar/pulsar:2.7.0
    expose:
      - 8080
      - 6650
    ports:
      - "6650:6650"
      - "80:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  #dashboard:
  #  image: apachepulsar/pulsar-dashboard
  #  depends_on:
  #    - standalone
  #  ports:
  #    - "80:80"
  #  environment:
  #    - SERVICE_URL=http://standalone:8080

volumes:
  my-db-zelda:
